#!/usr/bin/env python3
"""Render terms_table.json as LaTeX (TERMS.tex): a standalone-compilable
document whose table bodies can be lifted directly into a paper.

Layout: one suite-overview table (booktabs), then one longtable per
kernel x model with every principal term: order, DMD coefficient, kind,
distance polynomial (cache lines), population polynomial (accesses),
portion of accesses, and the source access(es) the bin belongs to.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

PREAMBLE = r"""% Auto-generated by build_terms_tex.py — principal contribution terms
% of the PolyBench kernels (exact Barvinok counting, block = 8 doubles).
% The longtable bodies can be copied straight into a paper.
\documentclass[9pt]{extarticle}
\usepackage[margin=2cm,landscape]{geometry}
\usepackage{booktabs,longtable,amsmath,array}
\usepackage[T1]{fontenc}
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.15}
\newcommand{\src}[1]{\texttt{\footnotesize #1}}
\begin{document}

\section*{Principal contribution terms of the PolyBench kernels}

Each reuse-distance bin of a kernel is a term $(V(n), M(n))$: a distance
$V(n)$ in 64-byte cache lines and a population $M(n)$ in accesses, both
exact in the problem size $n$ (all parameters bound to $n$; convolution's
filter extent fixed at $9$; arrays row-padded to line multiples). The term
contributes $M(n)$ misses exactly on the cache range $C < V(n)$ (boundary
$64\,V(n)$ bytes, portion $M/A$ of all accesses) and $M\sqrt{V}$ to the
data-movement sum (order $n^{\deg M + \deg V/2}$). A \emph{level} holds one
distance; a \emph{ramp} spans $[V_{\min}, V_{\max}]$ along a loop iterator
and its misses taper across that range. Polynomials are exact on the anchor
class $n \equiv 0 \pmod h$ ($h = 8$ or $16$ per kernel); ramp coefficients
are evaluated at the anchor sizes. All kernels ran with exact counting:
$\sum M$ equals the warm-access count to the integer, and the reconstructed
histograms match a reference trace interpreter bin for bin.
"""


def tex_escape(s):
    return s.replace("_", "\\_")


def poly_tex(s):
    """'(1/8)·n^2 + (3/8)·n + 1' -> '\\tfrac{1}{8}n^2 + \\tfrac{3}{8}n + 1'
    (also handles '→' range arrows and slope-estimate annotations)."""
    if s is None:
        return "?"
    s = str(s)
    s = s.replace("→", r"\;\ldots\;")
    s = re.sub(r"\((\-?\d+)/(\d+)\)", r"\\tfrac{\1}{\2}", s)
    s = s.replace("·", r"\,")
    s = re.sub(r"\^(\-?\d+(?:\.\d+)?)", r"^{\1}", s)
    s = s.replace(" (slope estimate)", r"\ \text{(slope est.)}")
    s = s.replace("~", r"{\sim}")
    return s


def coeff_tex(c):
    if c == 0:
        return "0"
    if abs(c) >= 1000:
        return f"{c:,.0f}".replace(",", r"\,")
    s = f"{c:.3g}"
    if "e" in s:
        m, e = s.split("e")
        return f"{m}\\cdot 10^{{{int(e)}}}"
    return s


def portion_tex(t):
    if "portion_deg" not in t:
        return "--"
    d, l = t["portion_deg"], t["portion_lead"]
    if d == 0:
        return f"${coeff_tex(l)}$"
    if d == -1:
        return f"${coeff_tex(l)}/n$"
    return f"${coeff_tex(l)}\\,n^{{{d}}}$"


def order_tex(o):
    return f"$n^{{{o:g}}}$"


def suite_table(table):
    rows = []
    def sort_key(k):
        rec = table[k]
        return (-(rec["headroom"] or 0), rec["kernel"], k.rsplit(".", 1)[1])
    for key in sorted(table, key=sort_key):
        rec = table[key]
        name = tex_escape(rec["kernel"].replace("sym_", ""))
        model = key.rsplit(".", 1)[1]
        model = "single" if model == "single" else "repeat"
        top = ",\\; ".join(f"{coeff_tex(c)}\\,n^{{{o:g}}}"
                           for o, c in rec["spectrum"][:2])
        rows.append(f"{name} & {model} & {rec['access_deg']} & "
                    f"{rec['dmd_order']:g} & ${rec['headroom']:+g}$ & "
                    f"${top}$ \\\\")
    return "\n".join([
        r"\subsection*{Suite overview}",
        r"\begin{longtable}{l l c c c l}",
        r"\toprule",
        r"kernel & model & $a$ & $d$ & headroom & leading terms \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{longtable}",
    ])


def kernel_table(key, rec):
    name = tex_escape(rec["kernel"].replace("sym_", ""))
    model = "single-shot" if key.endswith(".single") else "infinite-repeat"
    cons = rec.get("conservation", [])
    cons_txt = ", ".join(f"{c['ratio']:.6g}" for c in cons
                         if c["ratio"] is not None)
    head = [
        f"\\subsection*{{{name} --- {model} "
        f"[\\texttt{{{rec['method']}}}]}}",
        f"$A(n) = {poly_tex(rec['access_poly'])}$ "
        f"(exact on $n \\equiv {rec['anchor_base'] % rec['modulus']} "
        f"\\bmod {rec['modulus']}$); "
        f"DMD order $n^{{{rec['dmd_order']:g}}}$, "
        f"headroom $\\mathbf{{{rec['headroom']:+g}}}$; "
        f"$\\sum M/\\mathrm{{warm}} = {cons_txt}$.",
        "",
        f"Spectrum: $"
        + " + ".join(f"{coeff_tex(c)}\\,n^{{{o:g}}}"
                     for o, c in rec["spectrum"] if c >= 1e-6)
        + "$.",
        "",
        r"\begin{longtable}{l l l p{5.2cm} p{6.2cm} l p{4.6cm}}",
        r"\toprule",
        r"order & coeff & kind & distance $V(n)$ (lines) & "
        r"population $M(n)$ (accesses) & portion & source access \\",
        r"\midrule",
    ]
    rows = []
    for t in rec["terms"]:
        if t.get("portion_deg", 0) <= -rec["access_deg"] \
                and t["dmd_coeff"] < 1e-6:
            continue
        if t["kind"] == "level":
            dist = f"${poly_tex(t.get('value_poly', t['value_expr']))}$"
            kind = "level"
        else:
            lo, hi = t.get("value_range", ["?", "?"])
            dist = f"${poly_tex(lo)} \\;\\ldots\\; {poly_tex(hi)}$"
            kind = "ramp"
        pop = f"${poly_tex(t.get('mass_poly', ''))}$"
        srcs = "; ".join(tex_escape(s) for s in t.get("sources", [])[:2])
        if len(t.get("sources", [])) > 2:
            srcs += f" (+{len(t['sources']) - 2})"
        rows.append(f"{order_tex(t['dmd_order'])} & "
                    f"${coeff_tex(t['dmd_coeff'])}$ & {kind} & {dist} & "
                    f"{pop} & {portion_tex(t)} & \\src{{{srcs}}} \\\\")
    tail = [r"\bottomrule", r"\end{longtable}"]
    return "\n".join(head + rows + tail)


def main():
    table = json.load(open(f"{HERE}/terms_table.json"))
    parts = [PREAMBLE, suite_table(table)]
    for key in sorted(table):
        parts.append(kernel_table(key, table[key]))
    parts.append(r"\end{document}")
    open(f"{HERE}/TERMS.tex", "w").write("\n\n".join(parts) + "\n")
    print(f"wrote TERMS.tex ({len(table)} kernel-models)")


if __name__ == "__main__":
    main()
